global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email

receivers:
- name: email
  email_configs:
  - to: 'you@example.com'
    from: 'alertmanager@example.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'sergo'
    auth_password: '12345678'
    starttls_require: true
