global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['172.16.12.73:9100']

  - job_name: 'myapp'
    static_configs:
      - targets: ['myapp:8080']
