global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['172.16.10.210:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['172.16.10.210:9187']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['172.16.10.210:9093']
